schema: workflow/2022.04
name: Report Survey Orchestrator
settings:
  error_notification: true
  lambda_memory: 256
  lambda_timeout: 120
triggers:
- id: ti_nNTYl2G
steps:
- namespace: fan_out_reports
  runtime: nodejs20.x
  uses: "./fan_out_reports/entry.mjs"
